apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywisecow-app
  template:
    metadata:
      labels:
        app: mywisecow-app
    spec:
      containers:
        - name: mywisecow-app
          image: afzal442/wisecowapp:main
          ports:
            - containerPort: 4499
