apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wisecow-ingress
spec:
  tls:
    - hosts:
        - wisecow.app.co
      secretName: my-tls-secret
  rules:
    - host: wisecow.app.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wisecow-svc
                port:
                  number: 80
